[key_mappings]
"ctrl+alt+a" = "C:/windows/system32/notepad.exe"
"ctrl+alt+b" = "C:/windows/system32/cmd.exe"
"ctrl+space" = "C:/Repositories/arcade-station/src/arcade_station/kill_all_and_reset_pegasus.py" # Will be populated by installer eventually